# Generated by Django 5.0.3 on 2024-04-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bot_running', models.BooleanField(default=False)),
                ('volume', models.IntegerField()),
                ('leverage', models.IntegerField()),
                ('static_id', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
